# This is a basic workflow to help you get started with Actions

name: netlify-build

on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      env:
        NETLIFY_HASH: ${{ secrets.NETLIFY_HASH }}
      with:
        args: -X POST {} "https://api.netlify.com/build_hooks/$NETLIFY_HASH"
