name: netlify-build

on: push
jobs:
  build-hook:
    runs-on: ubuntu-latest
    steps:
    - name: "Build hook"
      env:
        NETLIFY_HASH: ${{ secrets.NETLIFY_HASH }}
      run: curl -X POST -d {} "https://api.netlify.com/build_hooks/$NETLIFY_HASH"
