name: Trigger netlify build

on: push

jobs:
  netlify-build:
    name: Netlify Build
    steps:
      - shell: bash
        env:
          NETLIFY_HASH: ${{ secrets.NETLIFY_HASH }}
          run: |
            curl -X POST -d {} 'https://api.netlify.com/build_hooks/'"$NETLIFY_HASH"
